### ISSUE TITLE
Can we stop using io.airlift.slice.RuntimeIOException ?

### ISSUE THREAD

**Issue by dmikurube** [jo8937/embulk-input-bigquery_extract_files#2]
@jo8937 
Hi, thanks for creating/maintaining this Embulk plugin! I'm the current maintainer of Embulk.

We now plan to remove `io.airlift:slice` from `embulk-core`'s dependency libraries. (More precisely, hiding it from plugins.) Once we do it, I guess this part would not work.

https://github.com/jo8937/embulk-input-bigquery_extract_files/blob/3e27ae8929793228f33f100c71d451ee8c05442d/src/main/java/org/embulk/input/bigquery_export_gcs/BigqueryExportGcsFileInputPlugin.java#L32

Is it possible to stop using `io.airlift.slice.RuntimeIOException`? I guessed you just wanted an unchecked `IOException` here. If so, replacing it with `java.io.UncheckedIOException` could help.

**Comment by jo8937** [comment]
Thanks for your notification!
OK. I'll try remove that.

**Comment by dmikurube** [comment]
Thanks for your quick response!
